export const WS_OPEN_CONNECTION_PENDING = 'WS_OPEN_CONNECTION_PENDING';
export const WS_OPEN_CONNECTION_SUCCESS = 'WS_OPEN_CONNECTION_SUCCESS';
export const WS_OPEN_CONNECTION_FAIL = 'WS_OPEN_CONNECTION_FAIL';

export const WS_CLOSE_CONNECTION = 'WS_CLOSE_CONNECTION';

export const IFNO_RECEIVED = 'IFNO_RECEIVED';
export const ERROR_RECEIVED = 'ERROR_RECEIVED';
